### ISSUE TITLE
Ссылка на скрипт из EvoCollection

### ISSUE THREAD

**Issue by dukeRD** [liber87/evopuck#1]
https://github.com/liber87/evopuck/blob/b8fb79ec27c35df226a20a4b90ee2e125417b6de/assets/modules/evopuck/evopuck.module.php#L360

Не лучше ли включить скрипт в пакет модуля, если он действительно нужен, и не зависеть от установки сторонних плагинов?

**Comment by liber87** [comment]
да, спасибо, он там вообще нахер не нужен был.
